<?php

namespace AppBundle\Repository;

use UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserUnreadNotifications(User $user)
    {
        return $this->createQueryBuilder("n")
            ->select("n")
            ->where("n.unread = 1")
            ->andWhere("n.user = :user")->setParameter("user", $user)
            ->getQuery()->getResult();

    }
}
